SOURCECODE/WebApplication2/Controllers/BillController.cs
using BLL;
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class BillController : Controller
    {
        BillBLL billDLL = new BillBLL();

        public ActionResult Index()
        {
            ViewBag.error = TempData["Message"];
            return View(billDLL.getAllBill());
        }

        //XÓA HÓA ĐƠN
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Bill bill = billDLL.findBill(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bill bill = billDLL.findBill(id);
            billDLL.deleteBill(bill);
            TempData["Message"] = "Xóa hóa đơn thành công !";
            return RedirectToAction("Index");
        }

        //XEM CHI TIẾT HÓA ĐƠN
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = billDLL.findBill(id);

            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }
    }
}

SOURCECODE/WebApplication2/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BLL;
using Entities;

namespace WebApplication2.Controllers
{
    public class CustomerController : Controller
    {
        CustomerBLL cusBLL = new CustomerBLL();

        // GET: Customer
        public ActionResult Index()
        {
            eCustomer c = cusBLL.GetCustomer(int.Parse(Session["id"].ToString()));
            return View(c);
        }      
        // GET: Tours/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            eCustomer c = cusBLL.GetCustomer(id);
            if (c == null)
            {
                return HttpNotFound();
            }
            return View(c);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "customerID,customerName,IDCard,phone,address")] eCustomer c)
        {
            if (ModelState.IsValid)
            {
                cusBLL.editCustomer(c);
                TempData["Message"] = "Cập nhập thông tin thành công !";
                return RedirectToAction("Index");
            }
            return View(c);
        }

    }
}

SOURCECODE/WebApplication2/Controllers/FeedbackController.cs
using BLL;
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class FeedbackController : Controller
    {
        FeedbackBLL fb = new FeedbackBLL();

        public ActionResult Index()
        {
            ViewBag.error = TempData["Message"];
            return View(fb.getAllFeedback());
        }

        //XÓA HÓA ĐƠN
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            eFeedback e = fb.findFeedback(id);
            if (e == null)
            {
                return HttpNotFound();
            }
            return View(e);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            eFeedback e = fb.findFeedback(id);
            fb.deleteFeedback(e);
            TempData["Message"] = "Xóa phản hồi thành công !";
            return RedirectToAction("Index");
        }

        //XEM CHI TIẾT HÓA ĐƠN
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            eFeedback e = fb.findFeedback(id);

            if (e == null)
            {
                return HttpNotFound();
            }
            return View(e);
        }
    }
}

SOURCECODE/WebApplication2/Controllers/TourController.cs
using BLL;
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class TourController : Controller
    {
        TourBLL tourBLL = new TourBLL();

        // GET: Tour
        public ActionResult Index()
        {
            ViewBag.error = TempData["Message"];
            return View(tourBLL.getAll());
        }       

        // GET: Tours/Create
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "tourName,departureDate,numberOfDay,startAddress,price,numSeat,emptySeat,tourType")] Tour tour)
        {
            var fhinh = Request.Files[0];
            var path = Server.MapPath("~/Images/" + fhinh.FileName);
            fhinh.SaveAs(path);

            tour.Picture = fhinh.FileName;

            if (ModelState.IsValid)
            {
                tourBLL.addTour(tour);
                TempData["Message"] = "Thêm tour mới thành công !";
                return RedirectToAction("Index");
            }
            return View(tour);
        }

        // GET: Tours/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tour tour = tourBLL.findTour(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            return View(tour);
        }

        // POST: Tours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tour tour = tourBLL.findTour(id);
            tourBLL.deleteTour(tour);
            TempData["Message"] = "Xóa tour thành công !";
            return RedirectToAction("Index");
        }

        // GET: Tours/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tour tour = tourBLL.findTour(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            return View(tour);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "tourID,tourName,departureDate,numberOfDay,startAddress,price,numSeat,emptySeat,tourType")] Tour tour)
        {
            if (ModelState.IsValid)
            {
                tourBLL.editTour(tour);
                TempData["Message"] = "Cập nhập tour thành công !";
                return RedirectToAction("Index");
            }
            return View(tour);
        }
        // GET: Tours/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tour tour = tourBLL.findTour(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            return View(tour);
        }
    }
}

SOURCECODE/WebApplication2/Views/Shared/Layout_Empty.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!--BUTTON TOP-->
    <!------------------------------------------------------------------------>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            if ($(".btn-top").length > 0) {
                $(window).scroll(function () {
                    var e = $(window).scrollTop();
                    if (e > 300) {
                        $(".btn-top").show()
                    } else {
                        $(".btn-top").hide()
                    }
                });
                $(".btn-top").click(function () {
                    $('body,html').animate({
                        scrollTop: 0
                    })
                })
            }
        });
    </script>
    <div class="footer"> <a class="btn-top" href="javascript:void(0);" title="Top" style="display: inline;"></a> </div>
    <style>
        .btn-top {
            background-image: url('../../Images/topBtn.jpg');
            background-repeat: no-repeat;
            border: medium none;
            bottom: 20px;
            cursor: pointer;
            display: none;
            height: 50px;
            outline: medium none;
            padding: 0;
            position: fixed;
            right: 20px;
            width: 50px;
            z-index: 9999;
        }
    </style>
    <!-- NAVIGATION BAR -->
    <!------------------------------------------------------------------------------>
    <nav class="navbar navbar-expand-sm bg-info navbar-dark fixed-top">
        <!-- Brand -->
        <a class="navbar-brand" href="#">
            <img src="~/Images/travel-and-tourism.png" alt="Logo" style="width:40px;"><b>TravelIUH</b>
        </a>

        <!-- Links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                @Html.ActionLink("Trang chủ", "Index", "Home", null, new { @class = "nav-link" })
            </li>

            <!-- Dropdown -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    Du lịch
                </a>
                <div class="dropdown-menu">
                    @Html.ActionLink("Tour trong nước", "TourType", "Home", new { i = 1 }, new { @class = "dropdown-item" })
                    @Html.ActionLink("Tour nước ngoài", "TourType", "Home", new { i = 0 }, new { @class = "dropdown-item" })
                </div>
            </li>

            <li class="nav-item">
                @Html.ActionLink("Giới thiệu", "About", "Home", new { @class = "nav-link" })
            </li>
            @if (Session["FullName"] != null)
            {
                if (Session["FullName"].ToString().Equals("admin"))
                {
                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            Bảng quản trị
                        </a>
                        <div class="dropdown-menu">
                            @Html.ActionLink("Quản lý tour", "Index", "Tour", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Quản hóa đơn", "Index", "Bill", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Quản hóa phản hồi", "Index", "Feedback", null, new { @class = "dropdown-item" })
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            @Session["FullName"].ToString()
                        </a>
                        <div class="dropdown-menu">
                            @Html.ActionLink("Đăng xuất", "Logout", "Home", null, new { @class = "dropdown-item" })
                        </div>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        @Html.ActionLink("Phản hồi", "FeedBack", "Home", null, new { @class = "nav-link" })
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            @Session["FullName"].ToString()
                        </a>
                        <div class="dropdown-menu">
                            @Html.ActionLink("Thông tin", "Index", "Customer", new { id = int.Parse(@Session["id"].ToString()) }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Đăng xuất", "Logout", "Home", null, new { @class = "dropdown-item" })
                        </div>
                    </li>
                }
            }
            else
            {
                <li>@Html.ActionLink("Đăng nhập", "Login", "Home", new { @class = "nav-link" })</li>
                <li>@Html.ActionLink("Đăng ký", "Register", "Home", new { @class = "nav-link" })</li>
            }

        </ul>
    </nav>
    <br /><br />
    <!------------------------------------------------------------------------------>
    <!--BODY Ở CÁC VIEW-->
    <!------------------------------------------------------------------------>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Bài tập lớn môn lập trình WWW</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SOURCECODE/WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/css/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <!--BUTTON TOP-->
    <!------------------------------------------------------------------------>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            if ($(".btn-top").length > 0) {
                $(window).scroll(function () {
                    var e = $(window).scrollTop();
                    if (e > 300) {
                        $(".btn-top").show()
                    } else {
                        $(".btn-top").hide()
                    }
                });
                $(".btn-top").click(function () {
                    $('body,html').animate({
                        scrollTop: 0
                    })
                })
            }
        });
    </script>
    <div class="footer"> <a class="btn-top" href="javascript:void(0);" title="Top" style="display: inline;"></a> </div>
    <style>
        .btn-top {
            background-image: url('../../Images/topBtn.jpg');
            background-repeat: no-repeat;
            border: medium none;
            bottom: 20px;
            cursor: pointer;
            display: none;
            height: 50px;
            outline: medium none;
            padding: 0;
            position: fixed;
            right: 20px;
            width: 50px;
            z-index: 9999;
        }
    </style>

    <!-- NAVIGATION BAR -->
    <!------------------------------------------------------------------------------>
    <nav class="navbar navbar-expand-sm bg-info navbar-dark fixed-top">
        <!-- Brand -->
        <a class="navbar-brand" href="#">
            <img src="~/Images/travel-and-tourism.png" alt="Logo" style="width:40px;"><b>TravelIUH</b>
        </a>

        <!-- Links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                @Html.ActionLink("Trang chủ", "Index", "Home", null, new { @class = "nav-link" })
            </li>

            <!-- Dropdown -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    Du lịch
                </a>
                <div class="dropdown-menu">
                    @Html.ActionLink("Tour trong nước", "TourType", "Home", new { i = 1 }, new { @class = "dropdown-item" })
                    @Html.ActionLink("Tour nước ngoài", "TourType", "Home", new { i = 0 }, new { @class = "dropdown-item" })
                </div>
            </li>

            <li class="nav-item">
                @Html.ActionLink("Giới thiệu", "About", "Home", new { @class = "nav-link" })
            </li>
            @if (Session["FullName"] != null)
            {
                if (Session["FullName"].ToString().Equals("admin"))
                {
                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            Bảng quản trị
                        </a>
                        <div class="dropdown-menu">
                            @Html.ActionLink("Quản lý tour", "Index", "Tour", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Quản hóa đơn", "Index", "Bill", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Quản hóa phản hồi", "Index", "Feedback", null, new { @class = "dropdown-item" })
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            @Session["FullName"].ToString()
                        </a>
                        <div class="dropdown-menu">                          
                            @Html.ActionLink("Đăng xuất", "Logout", "Home", null, new { @class = "dropdown-item" })
                        </div>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        @Html.ActionLink("Phản hồi", "FeedBack", "Home", null, new { @class = "nav-link" })
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            @Session["FullName"].ToString()
                        </a>
                        <div class="dropdown-menu">
                            @Html.ActionLink("Thông tin", "Index", "Customer", new { id = int.Parse(@Session["id"].ToString()) }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Đăng xuất", "Logout", "Home", null, new { @class = "dropdown-item" })
                        </div>
                    </li>
                }
            }
            else
            {
                <li>@Html.ActionLink("Đăng nhập", "Login", "Home", new { @class = "nav-link" })</li>
                <li>@Html.ActionLink("Đăng ký", "Register", "Home", new { @class = "nav-link" })</li>
            }

        </ul>
    </nav>
    <br /><br />
    <!------------------------------------------------------------------------------>
    <!--BODY-->
          <div class="container body-content">
              <!--PHẦN HÌNH ẢNH-->
              <!------------------------------------------------------------------------>
              <div class="card">
                  <div class="card-body">
                      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                          <ol class="carousel-indicators">
                              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                          </ol>
                          <div class="carousel-inner">
                              <div class="carousel-item active">
                                  <img class="d-block w-100" src="~/Images/crs_1.jpg" alt="First slide" style="height:400px;width:100%;">
                                  <div class="carousel-caption d-none d-md-block">
                                      <h5>Phố cổ Hội An</h5>
                                      <p>Phố cổ Hội An là một đô thị cổ nằm ở hạ lưu sông Thu Bồn, thuộc vùng đồng bằng ven biển tỉnh Quảng Nam, Việt Nam, cách thành phố Đà Nẵng khoảng 30 km về phía Nam.Bắt đầu từ thập niên 1980, những giá trị kiến trúc và văn hóa của phố cổ Hội An dần được giới học giả và cả du khách chú ý, khiến nơi đây trở thành một trong những điểm du lịch hấp dẫn của Việt Nam.</p>
                                  </div>
                              </div>
                              <div class="carousel-item">
                                  <img class="d-block w-100" src="~/Images/crs_2.jpg" alt="Second slide" style="height:400px;width:100%;">
                                  <div class="carousel-caption d-none d-md-block">
                                      <h5>Phan Xi Păng</h5>
                                      <p>Phan Xi Păng, Fansipan, hay Phan Si Păng là ngọn núi cao nhất Việt Nam, cũng là cao nhất trong ba nước Đông Dương nên được mệnh danh là "Nóc nhà Đông Dương" thuộc dãy núi Hoàng Liên Sơn, cách trung tâm thị xã Sa Pa khoảng 9 km về phía tây nam, nằm giáp hai tỉnh Lào Cai và Lai Châu thuộc vùng Tây bắc Việt Nam. Theo tiếng địa phương, núi tên là "Hủa Xi Pan" và có nghĩa là phiến đá khổng lồ chênh vênh. Chiều cao của đỉnh núi đo đạc năm 1909 là 3.143m.</p>
                                  </div>
                              </div>
                              <div class="carousel-item">
                                  <img class="d-block w-100" src="~/Images/crs_3.jpg" alt="Third slide" style="height:400px;width:100%;">
                                  <div class="carousel-caption d-none d-md-block">
                                      <h5>Nhật Bản mùa hoa anh đào</h5>
                                      <p>Thời khắc kỳ diệu của cả năm ở Nhật Bản đang đến, khi quốc hoa của nước này, Sakura (hoa anh đào) sẽ đua nở trên khắp đất nước Nhật Bản xinh đẹp. Cả nước Nhật như khoác lên mình một bộ lễ phục lộng lẫy dệt bởi hoa cỏ mùa xuân.</p>
                                  </div>
                              </div>
                          </div>
                          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                              <span class="sr-only">Previous</span>
                          </a>
                          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                              <span class="carousel-control-next-icon" aria-hidden="true"></span>
                              <span class="sr-only">Next</span>
                          </a>
                      </div>
                  </div>
              </div>
              <br /><br />
              <!--BODY Ở CÁC VIEW-->
              <!------------------------------------------------------------------------>
              @RenderBody()
              <hr />
              <footer>
                  <p>&copy; @DateTime.Now.Year - Bài tập lớn môn lập trình WWW</p>
              </footer>
          </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>